export const types = {
    openModalImage: '[ui] open-Modal-Image',
    closeModalImage: '[ui] close-Modal-Image',
    openModalSuscribe: '[ui] open-Modal-Suscribe',
    closeModalSuscribe: '[ui] close-Modal-Suscribe',
    closeAllModals: '[ui] close-All-Modals',
    uiLogout: '[ui] logout',
    loadigApp: '[ui] loadingApp',
    userLoged: '[data] userLoged',
    userLogout: '[data] user-Logout',
    updateUserLoged: '[data] userUpdate',
    associationFromRegio: '[data-asc] FromRegion',
    restAssociationFromRegio: '[data-asc] Reset-Asc-From-Regin',
    addAllMyEvents: '[ event-user ] Add-all-my-event',
    resetMyEvent: '[ event-user ] Reset-my-event',
    deleteMyEvent: '[ event-user ] Delete-my-event(s)',
    getMyEvent: '[ event-user ] Get-my-events',
    addGroupsEvent: '[ groups-event ] Add-Groups',
    resetGroups:'[ groups-event ] Reset-Groups',
    addAllFavoriteAsc: '[ favorite ] Add-all-favorite',
    addToFavorite: '[ favorite ] Add-To-favorite',
    resetFavorites: '[ favorite ] Reset-favorites',
    removeFavorite: '[ favorite ] Remove-favorite'
}