export const types = {
    openModalImage: '[ui] open-Modal-Image',
    closeModalImage: '[ui] close-Modal-Image',
    openModalSuscribe: '[ui] open-Modal-Suscribe',
    closeModalSuscribe: '[ui] close-Modal-Suscribe',
    closeAllModals: '[ui] close-All-Modals',
    loadigApp: '[ui] loadingApp',
    userLoged: '[data] userLoged',
    updateUserLoged: '[data] userUpdate',
    associationFromRegio: '[data-asc] FromRegion',
    getHistoryRouter: '[router] history',
    addMyEvent: '[ event-user ] Add-my-event',
    deleteMyEvent: '[ event-user ] Delete-my-event(s)',
    getMyEvent: '[ event-user ] Get-my-events',
}